-- Run this in your Supabase SQL Editor to create the required tables for Arboretum

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.user_profiles (
    id uuid PRIMARY KEY,
    display_name text DEFAULT 'Forest Keeper',
    profile_pic text DEFAULT 'https://picsum.photos/seed/keeper/200',
    total_focus_seconds integer DEFAULT 0,
    giveup_count integer DEFAULT 0,
    hour_model jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.sessions (
    id bigint generated by default as identity primary key,
    user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    duration_mins integer NOT NULL,
    goal_mins integer NOT NULL,
    completed boolean NOT NULL,
    hour integer NOT NULL,
    date text NOT NULL,
    day_of_week integer NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous access for the app functionality
CREATE POLICY "Enable all operations for user_profiles" ON public.user_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for sessions" ON public.sessions FOR ALL USING (true) WITH CHECK (true);
